project:
  type: website
  output-dir: docs

website:
  title: "WANGANLIN's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/wanganlin00
      


theme:
  light: flatly
  dark: darkly

execute: 
  warning: false
  message: false
  cache: true

toc: true
code-fold: true
code-summary: "Show the code"
code-link: true

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

