project:
  type: website
  output-dir: docs

website:
  title: "Blog"
  navbar: 
    right:
      - about.qmd
      - icon: github
        href: https://github.com/wanganlin00
      
theme:
  light: flatly
  dark: darkly

execute: 
  warning: false
  message: false
  
toc: true
code-fold: true
code-summary: "Show the code"
code-link: true


format:
  html:
    theme: cosmo


editor: visual

